# Building rpms for Fedora 27
FROM: fedora:27

# Baseline of what we need in order to spin an rpm using kernel sources from kernel.org
RUN: dnf -y install kernel
RUN: dnf -y install gcc make rpm-build bc openssl
RUN: dnf -y install openssl-devel elfutils-libelf-devel 

# Now that requirements are done, lets copy in our kernel build automation script
{ TODO }

# Build and copy back the kernel
{ TODO }
